# Generated by Django 6.0.2 on 2026-04-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_jugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='background_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='foto_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
